apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - name: landing
        image: luchanso/landing:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
